### PR TITLE
Clicky planets

### PR DESCRIPTION
**Pull request by mitchellblom**
@blairvansant @owenherndon these are class notes, but zoe still would like one of y'all to okay it before merge.

### CODE REVIEW

**Comment by mitchellblom** [comment]
@blairvansant @owenherndon any revisions necessary here?

**Comment by OwenHerndon** [comment]
Nice visuals. Code looks great!

Got a few console logs in your showPlanetName function that you could comment out, though keep them in the code or change to a note as its good practice to understand whats going on.

```
function showPlanetName(event){
	if(event.target.className === 'planetImage'){
	console.log("event worked", event);
	// console.log("unique ID", event.target.parentNode.id)
	console.log("text?", event.target.previousSibling);
	event.target.previousSibling.classList.toggle('hidden');
	}
}
```

Nice mouseover event!
Could add something like 
```
clearButton.addEventListener("mouseenter", cleanUp);
```
Instead of the commented out mouseleave.

Overall looks great! 

Poor pluto and its dwarf planet status.

**Comment by mitchellblom** [comment]
@OwenHerndon edits made. thanks!

**Comment by OwenHerndon** [comment]
Nice, dont forget to fully update readme before you merge.
👍

**Comment by mitchellblom** [comment]
Readme complete. Merging per Owen's +1

**Pull request merged**
